---
- name: Setup AWS credentials for CloudWatch Agent
  hosts: home_servers
  become: true

  tasks:
    - name: Create .aws directory if it doesn't exist
      ansible.builtin.file:
        path: /root/.aws
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Check if AmazonCloudWatchAgent section already exists
      ansible.builtin.lineinfile:
        path: /root/.aws/credentials
        regexp: '^\[AmazonCloudWatchAgent\]'
        state: absent
      check_mode: true
      register: cloudwatch_section_check
      changed_when: false

    - name: Add AmazonCloudWatchAgent credentials section
      ansible.builtin.blockinfile:
        path: /root/.aws/credentials
        create: true
        mode: '0600'
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK - AmazonCloudWatchAgent"
        block: |
          [AmazonCloudWatchAgent]
          region = {{ aws_region }}
          aws_access_key_id = {{ iam_user_access_key_id }}
          aws_secret_access_key = {{ iam_user_access_key_secret }}
      when: cloudwatch_section_check.found == 0
