---
- name: Remove AWS credentials for CloudWatch Agent
  hosts: home_servers
  become: true

  tasks:
    - name: Remove AmazonCloudWatchAgent credentials section
      ansible.builtin.blockinfile:
        path: /root/.aws/credentials
        marker: "# {mark} ANSIBLE MANAGED BLOCK - AmazonCloudWatchAgent"
        state: absent
